In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import random

first_names = list(dict.fromkeys([
    "pratiksha","Sandesha","Sujita","Kiran","Nabin","Rajesh","Ramesh","Ashish","Manish","Dipesh",
    "Bikash","Sandesh","Sujan","Kiran","Nabin","Rajesh","Ramesh","Ashish","Manish","Dipesh",
    "pratik","Rohan","Anish","Suman","Bibek","Prabin","Nischal","Sagar","Roshan","Aayush",
    "Bikash","Sandesh","Sujan","Kiran","Nabin","Rajesh","Ramesh","Ashish","Manish","Dipesh",
    "Rahul","Suraj","Samir","Sandeep","Prakash","Pawan","Niraj","Rajan","Arjun","Amit",
    "Anil","Sunil","Santosh","Binod","Bimal","Dinesh","Deepak","Rupesh","Suresh","Siddharth",
    "Sophia","Emma","Olivia","Ava","Mia","Isabella","mahabati","Charlotte","Amelia","Harper",
    "Evelyn","Ella","Grace","govin","Lily","Arya","Zoe","Hina","Maya","Sofia",
    "Liam","Noah","Oliver","James","William","Henry","Lucas","Benjamin","Theodore","Jack",
    "Daniel","Michael","Alex","Mathun","john","David","Samuel","John","grishma","Leo"
]))

In [5]:
last_names = [
    "chaudhary","Thapa","thandar","Gurung","Shrestha","Rai","Tamang","KC","Adhikari","Poudel",
    "Bhandari","Gautam","Basnet","Bhattarai","Maharjan","Lama","Magar","Rana","Joshi","Dahal",
    "Khanal","Acharya","gacchadar","Pandey","Bista","Bohara","Chaudhary","Yadav","Mishra","Singh",
    "Johnson","tabdar","Williams","Brown","Jones","Miller","Davis","Wilson","Taylor","sharma",
    "sardar","majhi","uraw","Jackson","White","Harris","Clark","Lewis","Young","Walker"
]

In [6]:
job_titles = [
    "Data Analyst","Software Engineer","Business Analyst","Data Scientist",
    "HR Manager","Marketing Analyst","Financial Analyst","Project Manager",
    "Web Developer","QA Engineer"
]

In [7]:
random.seed(42)
all_names = list({f"{first} {last}" for first in first_names for last in last_names})
random.shuffle(all_names)
names = all_names[:1050]

df = pd.DataFrame({
    "id": range(1, 1051),
    "name": names,
    "salary": [random.randint(30000, 150000) for _ in range(1050)],
    "job_title": [random.choice(job_titles) for _ in range(1050)]
})

df.to_csv("company_data_1050.csv", index=False)

In [8]:
print("total data:", len(df))
print("duplicate checking:", df["name"].duplicated().sum())
df

total data: 1050
duplicate checking: 0

        id              name  salary          job_title
0        1       Sandesha KC  130511        QA Engineer
1        2     Evelyn sharma  106544       Data Analyst
2        3    Pawan Bhandari   60508   Business Analyst
3        4     Roshan tabdar   50922    Project Manager
4        5    Anish Bhandari   43124    Project Manager
...    ...               ...     ...                ...
1045  1046   Harper Adhikari   53758   Business Analyst
1046  1047  Olivia gacchadar  110127  Financial Analyst
1047  1048  Sandeep Bhandari   79774  Software Engineer
1048  1049   Suraj Chaudhary  132126  Software Engineer
1049  1050        Zoe Pandey   77002  Software Engineer

[1050 rows x 4 columns]

In [9]:
df.head(4)

   id            name  salary         job_title
0   1     Sandesha KC  130511       QA Engineer
1   2   Evelyn sharma  106544      Data Analyst
2   3  Pawan Bhandari   60508  Business Analyst
3   4   Roshan tabdar   50922   Project Manager

In [10]:
df.describe()

                id         salary
count  1050.000000    1050.000000
mean    525.500000   90542.318095
std     303.253195   35276.348683
min       1.000000   30089.000000
25%     263.250000   59286.250000
50%     525.500000   90106.000000
75%     787.750000  121249.500000
max    1050.000000  149822.000000